version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mount local code to container
      - ./node_modules:/app/node_modules  # Mount node_modules from the local machine
    environment:
      - NODE_ENV=development  # Set environment to development
    command: ["sh", "-c", "npm install && npm run dev"]  # Install dependencies and then run Next.js development server
